# Generated by Django 5.1.4 on 2024-12-31 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='XRayImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='xray_images/')),
                ('patient_name', models.CharField(blank=True, default='No data', max_length=100)),
                ('patient_surname', models.CharField(blank=True, default='No data', max_length=100)),
                ('patient_id', models.CharField(blank=True, default='No data', max_length=50)),
                ('patient_date_of_birth', models.CharField(blank=True, default='No data', max_length=20)),
                ('patient_gender', models.CharField(blank=True, default='No data', max_length=20)),
                ('xray_date', models.CharField(blank=True, default='No data', max_length=20)),
                ('prediction', models.CharField(blank=True, max_length=20)),
                ('confidence', models.FloatField(default=0.0)),
                ('normal_probability', models.FloatField(default=0.0)),
                ('pneumonia_probability', models.FloatField(default=0.0)),
                ('processing_time', models.FloatField(default=0.0)),
                ('image_size', models.CharField(blank=True, max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
