# Generated by Django 5.1.4 on 2025-01-04 08:27

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='xrayimage',
            name='user',
            field=models.ForeignKey(default=core.models.get_default_user, on_delete=django.db.models.deletion.CASCADE, related_name='xray_images', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='xrayimage',
            name='confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='xrayimage',
            name='image_size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='xrayimage',
            name='normal_probability',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='xrayimage',
            name='patient_date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='xrayimage',
            name='patient_gender',
            field=models.CharField(default='No data', max_length=20),
        ),
        migrations.AlterField(
            model_name='xrayimage',
            name='patient_id',
            field=models.CharField(default='No data', max_length=50),
        ),
        migrations.AlterField(
            model_name='xrayimage',
            name='patient_name',
            field=models.CharField(default='No data', max_length=100),
        ),
        migrations.AlterField(
            model_name='xrayimage',
            name='patient_surname',
            field=models.CharField(default='No data', max_length=100),
        ),
        migrations.AlterField(
            model_name='xrayimage',
            name='abnormal_probability',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='xrayimage',
            name='prediction',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='xrayimage',
            name='processing_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='xrayimage',
            name='xray_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
