# Generated by Django 5.1.4 on 2024-12-30 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='xrayimage',
            name='image_size',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='xrayimage',
            name='normal_probability',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='xrayimage',
            name='pneumonia_probability',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='xrayimage',
            name='processing_time',
            field=models.FloatField(default=0.0),
        ),
    ]
