# Generated by Django 5.1.4 on 2025-01-04 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_xrayimage_user_alter_xrayimage_confidence_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xrayimage',
            name='user',
        ),
        migrations.AlterField(
            model_name='xrayimage',
            name='confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='xrayimage',
            name='image_size',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='xrayimage',
            name='normal_probability',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='xrayimage',
            name='patient_date_of_birth',
            field=models.CharField(blank=True, default='No data', max_length=20),
        ),
        migrations.AlterField(
            model_name='xrayimage',
            name='patient_gender',
            field=models.CharField(blank=True, default='No data', max_length=20),
        ),
        migrations.AlterField(
            model_name='xrayimage',
            name='patient_id',
            field=models.CharField(blank=True, default='No data', max_length=50),
        ),
        migrations.AlterField(
            model_name='xrayimage',
            name='patient_name',
            field=models.CharField(blank=True, default='No data', max_length=100),
        ),
        migrations.AlterField(
            model_name='xrayimage',
            name='patient_surname',
            field=models.CharField(blank=True, default='No data', max_length=100),
        ),
        migrations.AlterField(
            model_name='xrayimage',
            name='abnormal_probability',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='xrayimage',
            name='prediction',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='xrayimage',
            name='processing_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='xrayimage',
            name='xray_date',
            field=models.CharField(blank=True, default='No data', max_length=20),
        ),
    ]
