# Generated by Django 5.1.4 on 2025-01-04 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_xrayimage_user_alter_xrayimage_confidence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xrayimage',
            name='image_size',
            field=models.CharField(blank=True, default='No data', max_length=50),
        ),
        migrations.AlterField(
            model_name='xrayimage',
            name='prediction',
            field=models.CharField(blank=True, default='No data', max_length=20),
        ),
    ]
