# Generated by Django 5.1.4 on 2025-01-04 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_xrayimage_image_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xrayimage',
            name='image_size',
            field=models.CharField(default='No data', max_length=50),
        ),
        migrations.AlterField(
            model_name='xrayimage',
            name='patient_date_of_birth',
            field=models.CharField(default='No data', max_length=20),
        ),
        migrations.AlterField(
            model_name='xrayimage',
            name='patient_gender',
            field=models.CharField(default='No data', max_length=20),
        ),
        migrations.AlterField(
            model_name='xrayimage',
            name='patient_id',
            field=models.CharField(default='No data', max_length=50),
        ),
        migrations.AlterField(
            model_name='xrayimage',
            name='patient_name',
            field=models.CharField(default='No data', max_length=100),
        ),
        migrations.AlterField(
            model_name='xrayimage',
            name='patient_surname',
            field=models.CharField(default='No data', max_length=100),
        ),
        migrations.AlterField(
            model_name='xrayimage',
            name='xray_date',
            field=models.CharField(default='No data', max_length=20),
        ),
    ]
