# Generated by Django 5.1.4 on 2025-01-05 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_user_options_alter_xrayimage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined'], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AddField(
            model_name='user',
            name='language_preference',
            field=models.CharField(choices=[('en', 'English'), ('lt', 'Lithuanian')], default='en', help_text='Preferred language for the user interface.', max_length=10, verbose_name='language preference'),
        ),
    ]
