# Generated by Django 5.0.1 on 2025-01-07 11:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_user_options_user_language_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xrayimage',
            name='patient_date_of_birth',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='xrayimage',
            name='patient_gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('N', 'Not Specified')], default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='xrayimage',
            name='patient_id',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Patient ID can only contain letters, numbers, and hyphens', regex='^[A-Za-z0-9-]+$')]),
        ),
        migrations.AlterField(
            model_name='xrayimage',
            name='patient_name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='xrayimage',
            name='patient_surname',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='xrayimage',
            name='xray_date',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
