# Generated by Django 5.0.1 on 2025-03-29 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_xrayimage_patient_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='xrayimage',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='xrayimage',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
