# Generated by Django 5.0.1 on 2025-04-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_xrayimage_error_message_alter_xrayimage_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='xrayimage',
            name='abnormal_probability',
            field=models.FloatField(default=0.0),
        ),
    ]
